seed: 42
device: auto

data:
  root: ./data/seg
  img_dir: images
  mask_dir: masks
  mask_map: mask_map.json   
  img_size: [512, 512]
  folds: 5

training:
  epochs: 20
  batch_size: 2
  lr: 0.0005
  weight_decay: 0.0001
  num_workers: 0           
  save_dir: runs/seg

model:
  in_channels: 1
  out_channels: 1

loss:
  bce_weight: 0.5
  dice_weight: 0.5

